name: "🏗 Deploy Staging"
on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: "Deploy Staging"
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🏗 Install dependencies
        run: yarn

      - name: Build app
        run: yarn build
        env:
          APP_KEYS: ${{ secrets.APP_KEYS }}
          API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}

      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.BACKEND_IMAGE_NAME }}:latest
